--------------------------------------------------------
--  ÆÄÀÏÀÌ »ý¼ºµÊ - ¸ñ¿äÀÏ-4¿ù-25-2019   
--------------------------------------------------------
DROP TABLE "MYUSER1"."EMP_TABLE" cascade constraints;
--------------------------------------------------------
--  DDL for Table EMP_TABLE
--------------------------------------------------------

  CREATE TABLE "MYUSER1"."EMP_TABLE" 
   (	"EMPNO" CHAR(6 BYTE), 
	"EMPNAME" NVARCHAR2(50), 
	"EMPBIRTH" CHAR(8 BYTE), 
	"DEPTNO" CHAR(3 BYTE), 
	"HREDATE" CHAR(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTSA" ;
REM INSERTING into MYUSER1.EMP_TABLE
SET DEFINE OFF;
Insert into MYUSER1.EMP_TABLE (EMPNO,EMPNAME,EMPBIRTH,DEPTNO,HREDATE) values ('170001','È«±æµ¿','880212  ','001','2018-12-15');
Insert into MYUSER1.EMP_TABLE (EMPNO,EMPNAME,EMPBIRTH,DEPTNO,HREDATE) values ('170002','ÀÌ¸ù·æ','770215  ','003','2018-12-16');
Insert into MYUSER1.EMP_TABLE (EMPNO,EMPNAME,EMPBIRTH,DEPTNO,HREDATE) values ('170003','¼ºÃáÇâ','820513  ','003','2018-12-17');
Insert into MYUSER1.EMP_TABLE (EMPNO,EMPNAME,EMPBIRTH,DEPTNO,HREDATE) values ('170004','Àåº¸°í','941102  ','004','2018-03-01');
Insert into MYUSER1.EMP_TABLE (EMPNO,EMPNAME,EMPBIRTH,DEPTNO,HREDATE) values ('170005','ÀÓ²©Á¤','801212  ','001','2018-12-15');
--------------------------------------------------------
--  DDL for Index SYS_C007048
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYUSER1"."SYS_C007048" ON "MYUSER1"."EMP_TABLE" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTSA" ;
--------------------------------------------------------
--  Constraints for Table EMP_TABLE
--------------------------------------------------------

  ALTER TABLE "MYUSER1"."EMP_TABLE" ADD PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTSA"  ENABLE;
  ALTER TABLE "MYUSER1"."EMP_TABLE" MODIFY ("HREDATE" NOT NULL ENABLE);
  ALTER TABLE "MYUSER1"."EMP_TABLE" MODIFY ("DEPTNO" NOT NULL ENABLE);
  ALTER TABLE "MYUSER1"."EMP_TABLE" MODIFY ("EMPNAME" NOT NULL ENABLE);
