--여기는 관리자화면입니다.

CREATE TABLESPACE myts1 DATAFILE 'd:\bizwork\ordata\myts1.dbf' SIZE 100M AUTOEXTEND ON NEXT 1M;

CREATE USER user3 IDENTIFIED BY 1234 DEFAULT TABLESPACE myts1 ;

DROP USER user3 ;

GRANT CREATE SESSION TO user3;

GRANT RESOURCE TO user3 ;

GRANT CREATE TABLE TO user3;

CREATE TABLE [TABLE NAME](
);

GRANT SELECT, INSERT, UPDATE, DELETE TO [Table Name] user3;   --?

GRANT DBA TO user3;

