--여기는 관리자 화면입니다.

--TABLESPACE 생성
CREATE TABLESPACE myTBL1 DATAFILE 'D:/bizwork/ordata/mytbl_1.dbf' SiZE 100M AUTOEXTEND ON NEXT 1M;

CREATE USER myMem IDENTIFIED BY 1234 DEFAULT TABLESPACE myTBL1;

GRANT DBA TO myMem ;

