--여기는 관리자 화면입니다.

--TABLESPACE 생성
CREATE TABLESPACE gradeTS DATAFILE 'd:/bizwork/ordata/gradeTS.dbf' SIZE 100M AUTOEXTEND ON NEXT 100k;

CREATE USER gradeUSER IDENTIFIED BY 1234 DEFAULT TABLESPACE gradeTS;

GRANT DBA to gradeUSER;