--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-4岿-25-2019   
--------------------------------------------------------
DROP TABLE "BOOKRENTALSHOP"."TBL_BBS" cascade constraints;
DROP TABLE "BOOKRENTALSHOP"."TBL_BOOK" cascade constraints;
DROP TABLE "BOOKRENTALSHOP"."TBL_COMMET" cascade constraints;
DROP TABLE "BOOKRENTALSHOP"."TBL_RENT" cascade constraints;
--------------------------------------------------------
--  DDL for Table TBL_BBS
--------------------------------------------------------

  CREATE TABLE "BOOKRENTALSHOP"."TBL_BBS" 
   (	"ID" NUMBER, 
	"B_AUTH" NVARCHAR2(125), 
	"B_DATE" VARCHAR2(10 BYTE), 
	"B_TIME" VARCHAR2(10 BYTE), 
	"B_SUBJECT" NVARCHAR2(125), 
	"B_TEXT" NVARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL" ;
--------------------------------------------------------
--  DDL for Table TBL_BOOK
--------------------------------------------------------

  CREATE TABLE "BOOKRENTALSHOP"."TBL_BOOK" 
   (	"BOOK_SEQ" NUMBER, 
	"BOOK_ISBN" CHAR(13 BYTE), 
	"BOOK_TITLE" NVARCHAR2(100), 
	"BOOK_AUTHOR" NVARCHAR2(100), 
	"BOOK_PRICE" NUMBER, 
	"BOOK_DESCRIPTION" NVARCHAR2(1000), 
	"BOOK_IMAGE" NVARCHAR2(125), 
	"BOOK_LINK" NVARCHAR2(255), 
	"BOOK_RENT_YN" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL" ;
--------------------------------------------------------
--  DDL for Table TBL_COMMET
--------------------------------------------------------

  CREATE TABLE "BOOKRENTALSHOP"."TBL_COMMET" 
   (	"ID" NUMBER, 
	"B_ID" NUMBER, 
	"C_AUTH" NVARCHAR2(125), 
	"C_DATE" VARCHAR2(10 BYTE), 
	"C_TIME" VARCHAR2(10 BYTE), 
	"C_TEXT" NVARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL" ;
--------------------------------------------------------
--  DDL for Table TBL_RENT
--------------------------------------------------------

  CREATE TABLE "BOOKRENTALSHOP"."TBL_RENT" 
   (	"RENT_SEQ" NUMBER, 
	"RENT_DATE" CHAR(10 BYTE), 
	"RENT_RETURN_DATE" CHAR(10 BYTE), 
	"BOOK_SEQ" NUMBER, 
	"USER_SEQ" NUMBER, 
	"RENT_RETURN_YN" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL" ;
REM INSERTING into BOOKRENTALSHOP.TBL_BBS
SET DEFINE OFF;
REM INSERTING into BOOKRENTALSHOP.TBL_BOOK
SET DEFINE OFF;
REM INSERTING into BOOKRENTALSHOP.TBL_COMMET
SET DEFINE OFF;
REM INSERTING into BOOKRENTALSHOP.TBL_RENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007389
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKRENTALSHOP"."SYS_C007389" ON "BOOKRENTALSHOP"."TBL_BBS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL" ;
--------------------------------------------------------
--  DDL for Index SYS_C007376
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKRENTALSHOP"."SYS_C007376" ON "BOOKRENTALSHOP"."TBL_BOOK" ("BOOK_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL" ;
--------------------------------------------------------
--  DDL for Index SYS_C007392
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKRENTALSHOP"."SYS_C007392" ON "BOOKRENTALSHOP"."TBL_COMMET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL" ;
--------------------------------------------------------
--  DDL for Index SYS_C007387
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKRENTALSHOP"."SYS_C007387" ON "BOOKRENTALSHOP"."TBL_RENT" ("RENT_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL" ;
--------------------------------------------------------
--  Constraints for Table TBL_BBS
--------------------------------------------------------

  ALTER TABLE "BOOKRENTALSHOP"."TBL_BBS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL"  ENABLE;
  ALTER TABLE "BOOKRENTALSHOP"."TBL_BBS" MODIFY ("B_AUTH" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_BOOK
--------------------------------------------------------

  ALTER TABLE "BOOKRENTALSHOP"."TBL_BOOK" ADD PRIMARY KEY ("BOOK_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL"  ENABLE;
  ALTER TABLE "BOOKRENTALSHOP"."TBL_BOOK" MODIFY ("BOOK_TITLE" NOT NULL ENABLE);
  ALTER TABLE "BOOKRENTALSHOP"."TBL_BOOK" MODIFY ("BOOK_ISBN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_COMMET
--------------------------------------------------------

  ALTER TABLE "BOOKRENTALSHOP"."TBL_COMMET" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL"  ENABLE;
  ALTER TABLE "BOOKRENTALSHOP"."TBL_COMMET" MODIFY ("C_AUTH" NOT NULL ENABLE);
  ALTER TABLE "BOOKRENTALSHOP"."TBL_COMMET" MODIFY ("B_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_RENT
--------------------------------------------------------

  ALTER TABLE "BOOKRENTALSHOP"."TBL_RENT" ADD PRIMARY KEY ("RENT_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKRENTAL"  ENABLE;
  ALTER TABLE "BOOKRENTALSHOP"."TBL_RENT" MODIFY ("USER_SEQ" NOT NULL ENABLE);
  ALTER TABLE "BOOKRENTALSHOP"."TBL_RENT" MODIFY ("BOOK_SEQ" NOT NULL ENABLE);
  ALTER TABLE "BOOKRENTALSHOP"."TBL_RENT" MODIFY ("RENT_RETURN_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOOKRENTALSHOP"."TBL_RENT" MODIFY ("RENT_DATE" NOT NULL ENABLE);
