--------------------------------------------------------
--  파일이 생성됨 - 목요일-4월-25-2019   
--------------------------------------------------------
DROP TABLE "USERCBT"."TBL_CBT" cascade constraints;
DROP TABLE "USERCBT"."TBL_TEST" cascade constraints;
--------------------------------------------------------
--  DDL for Table TBL_CBT
--------------------------------------------------------

  CREATE TABLE "USERCBT"."TBL_CBT" 
   (	"CB_NUM" CHAR(5 BYTE), 
	"CB_QUE" NVARCHAR2(125), 
	"CB_EX1" NVARCHAR2(125), 
	"CB_EX2" NVARCHAR2(125), 
	"CB_EX3" NVARCHAR2(125), 
	"CB_EX4" NVARCHAR2(125), 
	"CB_ANS" NVARCHAR2(125)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBTTS" ;
--------------------------------------------------------
--  DDL for Table TBL_TEST
--------------------------------------------------------

  CREATE TABLE "USERCBT"."TBL_TEST" 
   (	"ID" NUMBER, 
	"T_NUM" NVARCHAR2(10), 
	"T_TEXT" NVARCHAR2(125)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBTTS" ;
REM INSERTING into USERCBT.TBL_CBT
SET DEFINE OFF;
Insert into USERCBT.TBL_CBT (CB_NUM,CB_QUE,CB_EX1,CB_EX2,CB_EX3,CB_EX4,CB_ANS) values ('00002','어떤 명령이 수행되기 위해 가장 우선적으로 이루어져야하는 마이크로 오퍼레이션은?','1:MBR->IR','2:PC->MAR','3:PC+1->PC','4:PC->MBR','2');
Insert into USERCBT.TBL_CBT (CB_NUM,CB_QUE,CB_EX1,CB_EX2,CB_EX3,CB_EX4,CB_ANS) values ('00003','다음 PARALLEL PROCESS 중 PIPELINE PROCESS와 가장 관계가 깊은 것은?','1:SISD','2:SIMD','3:SIMD','4:MISD','1');
Insert into USERCBT.TBL_CBT (CB_NUM,CB_QUE,CB_EX1,CB_EX2,CB_EX3,CB_EX4,CB_ANS) values ('00004','64K DRAM 기억 소자를 이용하여 64K바이트 주 기억 장치를 구성하고자 한다. 이때 64K DRAM을 몇개 사용하여야 하는가?(단 K=Kilo이다.)','1:1','2:2','3:4','4:8','4');
Insert into USERCBT.TBL_CBT (CB_NUM,CB_QUE,CB_EX1,CB_EX2,CB_EX3,CB_EX4,CB_ANS) values ('00005','다음과 같이 표현되는 바이트머신의 데이터형식의 명칭으로 가장 옳은 것은?<부호,지수,가수>','1:고정소수점데이터','2:가변장논리데이터','3:부동소수점데이터','4:팩형식의 10진수','3');
REM INSERTING into USERCBT.TBL_TEST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007130
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERCBT"."SYS_C007130" ON "USERCBT"."TBL_CBT" ("CB_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBTTS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007149
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERCBT"."SYS_C007149" ON "USERCBT"."TBL_TEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBTTS" ;
--------------------------------------------------------
--  Constraints for Table TBL_CBT
--------------------------------------------------------

  ALTER TABLE "USERCBT"."TBL_CBT" ADD PRIMARY KEY ("CB_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBTTS"  ENABLE;
  ALTER TABLE "USERCBT"."TBL_CBT" MODIFY ("CB_EX4" NOT NULL ENABLE);
  ALTER TABLE "USERCBT"."TBL_CBT" MODIFY ("CB_EX3" NOT NULL ENABLE);
  ALTER TABLE "USERCBT"."TBL_CBT" MODIFY ("CB_EX2" NOT NULL ENABLE);
  ALTER TABLE "USERCBT"."TBL_CBT" MODIFY ("CB_EX1" NOT NULL ENABLE);
  ALTER TABLE "USERCBT"."TBL_CBT" MODIFY ("CB_QUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TEST
--------------------------------------------------------

  ALTER TABLE "USERCBT"."TBL_TEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBTTS"  ENABLE;
  ALTER TABLE "USERCBT"."TBL_TEST" MODIFY ("T_NUM" NOT NULL ENABLE);
